[versions]
# https://github.com/gradle-nexus/publish-plugin/releases
nexus = "2.0.0"

# https://docs.gradle.com/enterprise/gradle-plugin/#release_history
gradle-develocity = "3.19"
gradle-publish = "1.3.1"

# Version of Kotlin Gradle Plugin used for compilation.
kotlin-build = "2.1.10"

[libraries]
# Plugins as libraries. Used as dependencies for other plugins. it's a bit hacky way, but serves the purpose
#
# WARNING: it's a bit tricky this way to handle moves as gradle doesn't publihs them.

# Gradle
gradle-develocity = { module = "com.gradle.develocity:com.gradle.develocity.gradle.plugin", version.ref = "gradle-develocity" }
gradle-publish = { module = "com.gradle.plugin-publish:com.gradle.plugin-publish.gradle.plugin", version.ref = "gradle-publish" }

# Kotlin
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-build" }
kotlin-gradle-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin-build" }

[bundles]

[plugins]
nexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus" }
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish"}
kotlin-build = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-build"}
# Note: internal plugins cannot be used with `alias(libs.plugins....)`, because they don't have version.
