[versions]
# Tags: https://github.com/diffplug/spotless/tags
spotless = "6.25.0"

# Releases https://github.com/palantir/palantir-java-format/releases
spotless-palantir = "2.40.0"

[libraries]
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless"}

# Spotless formatting tools
spotless-palantir = { module = "com.palantir.javaformat:palantir-java-format", version.ref="spotless-palantir"}

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
