:plugin_major: 6
:demo-agp4: has been removed

:toc:
:toc-placement: preamble
:toclevels: 2
:showtitle:

= Basic plugin usage and support

This page shows plugin basic usage and support.

== Plugin requirements and compatibility

Plugin requires to work one of these plugins: `java`, `java library`, `Android application` or `Android library`.
These plugins can be applied directly or indirectly.

Additionally, plugin is compatible with `org.freefair.lombok`.

== Apply the plugin and basic settings

One should follow an https://plugins.gradle.org/plugin/org.jsonschema2dataclass[official Gradle guide] to apply the plugin.

Examples are provided in a table below to showcase `org.jsonschema2dataclass` plugin minimal configuration.
This way, extension `jsonSchema2Pojo` will be configured with an execution `example` in the `executions` container.

More detailed usage is documented in xref:parameters_{plugin_major}.adoc[parameters] section.

[options=header,cols="1,5"]
|=====
| DSL language | DSL example
// ------------------------------
| Groovy
a|
[source,groovy]
-----
plugins {
    id "java"
    id "org.jsonschema2dataclass" version "x.y.z"
}

jsonSchema2Pojo {
    executions {
        example {}
    }
}
-----
// ------------------------------
| Kotlin
a|
[source,kotlin]
-----
plugins {
    java
    id("org.jsonschema2dataclass") version "x.y.z"
}

jsonSchema2Pojo {
    executions {
        create("example") {
        }
    }
}
-----
// ------------------------------
|=====

== Processor dependencies

In some cases it is required to specify dependencies for a processor to
reference some JSON files via classpath or define plugin classes for a processor.

To achieve this, it is required to add these dependencies to `jsonschema2dataclassPlugins`
https://docs.gradle.org/current/userguide/dependency_management_terminology.html#sub:terminology_configuration[configuration].

NOTE: It's impossible to add a dependency from an output from an execution.

== Hooks and task dependencies

By default, plugin generates tasks to be run after process resources task, so the output from this task can be used.
Additionally, plugin tasks are configured to run before execution of compilation
and lombok (from `org.freefair.lombok`) processor.

== SDK and build tools support

.Demos and statuses
[options=header]
|=====
| SDK/Tool | Minimal Version | Maximum version | Notes
// ------------------------------
| Java compiler
| 8
| 19
|
// ------------------------------
| Gradle
| 6.0
| 7.x
| 8.0 support is currently in beta.
// ------------------------------
| Android Gradle Plugin
| 3
| 7
|
// ------------------------------
|=====

== Demos and their statuses

Project contains various minimal `org.jsonschema2dataclass` plugin usage https://github.com/jsonschema2dataclass/js2d-gradle/tree/main/demo[demos].
These minimal applications doesn't represent a normal full-featured applications for a given platform.
These application are included for a showcase plugin features and capabilities.

NOTE: Any additional ideas and contributions are welcome.

.Demos and statuses
[options=header]
|=====
| Platform | Demo | Status | Notes
// ------------------------------
.4+| JVM
| https://github.com/jsonschema2dataclass/js2d-gradle/tree/main/demo/java/groovy[Groovy DSL] example
| Maintained and healthy
| Demonstrates compatibility with Groovy DSL
// ------------------------------
| https://github.com/jsonschema2dataclass/js2d-gradle/tree/main/demo/java/kotlin[Kotlin DSL] example
| Maintained and healthy
| Demonstrates compatibility with Kotlin DSL and Kotlin language
// ------------------------------
| https://github.com/jsonschema2dataclass/js2d-gradle/tree/main/demo/java/model-publish[Model publishing] example
| Maintained and healthy
| Demonstrates a way to publish jars with sources and schemas along with classes
// ------------------------------
| https://github.com/jsonschema2dataclass/js2d-gradle/tree/main/demo/java/classpath[Plugin's processor classpath] examples
| Maintained and healthy
| Demonstrates usage for plugin's processor classpath manipulation to apply schemas and custom RuleFactory
// ------------------------------
.4+| Android
| https://github.com/jsonschema2dataclass/js2d-gradle/tree/main/demo/android-agp7[AGP 7] example
| Maintained and healthy
| Demonstrates usage in an android application
// ------------------------------
| AGP 4
| ⚠️ Demo has been removed since 6.0
a|

* AGP 4 API is used to bind to the Android project, so it's still technically supported.
* PR and support for a demo is welcome

// ------------------------------
|=====
