---
name: Android AGP 7 Demo CI

on:
  push:
    branches:
    - main
    tags-ignore:
    - '*'
    paths:
    - demo/android-agp7/**
    - .github/workflows/demo-android-agp7-ci.yml
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
    - demo/android-agp7/**
    - .github/workflows/demo-android-agp7-ci.yml

concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On master, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/main' && format('demo-agp7-ci-main-{0}', github.sha) || format('demo-agp7-ci-{0}', github.ref) }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

jobs:
  buildDemo:
    name: Build Android AGP 7 Demo
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/android-agp7
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        java: [17, 21]
        distribution: [zulu]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.distribution }} ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
        cache: gradle
    - name: Install Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.1.4
    - name: Build project Android AGP 7 Demo
      run: ./gradlew assembleDebug -S --scan --warning-mode all
